### ISSUE TITLE
fontScale not working in 1.17

### ISSUE THREAD

**Issue by Triplchii** [maruohon/minihud#149] opened 2021-06-12 12:26 UTC
Using the most recent release of minihud, whenever I try using the font scale option it doesn't change the size of the text and instead offsets it as if you were adjusting the x and y position of it. 
![2021-06-12_13 24 45](https://user-images.githubusercontent.com/85791098/121775798-9d95ec00-cb81-11eb-9e6b-39c0c0d07380.png)
![2021-06-12_13 24 59](https://user-images.githubusercontent.com/85791098/121775807-a38bcd00-cb81-11eb-8eda-70eaa6b72ea9.png)
These two screenshots show the fontscale at different settings, the top one is the default value of 0.5 and the bottom one is a value of 10. If i set the value to 0 the text disappears entirely.

**Comment by maruohon** [comment] 2021-06-12 18:42
I assume you mean the latest 1.17 version from CurseForge and not the earlier snapshot or pre4 versions? (The 1.17 versions are currently only uploaded to CurseForge.)

Some other people have also reported this, but it works in my test instances, even with Optifine.
![2021-06-12_21 39 36](https://user-images.githubusercontent.com/2331050/121786220-14090d00-cbc7-11eb-827f-20f49c9f5335.png)
![2021-06-12_21 39 50](https://user-images.githubusercontent.com/2331050/121786221-153a3a00-cbc7-11eb-989e-80f99c490cb8.png)

**Comment by Triplchii** [comment] 2021-06-12 20:39
Yeah the latest one on curseforge. also i tried it both with and without optifine and it didn't change anything

**Comment by SlenderFox** [comment] 2021-06-20 12:05
I just downloaded the 1.17 versions of MaLiLib and Minihud from curseforge and am having this issue aswell.

**Comment by maruohon** [comment] 2021-06-20 12:08
What other mods are you using? (pastebin the `latest.log` for example) I'm assuming this must be a mod conflict if it works for some people but not others. (Although the current malilib rendering code is hacky and temporary... but it seems to work when I test and use it myself.)

**Comment by SlenderFox** [comment] 2021-06-21 04:35
This issue happens even when the only mods are fabric-api, malilib, and minihud.
[latest.log](https://github.com/maruohon/minihud/files/6684057/latest.log)

**Comment by ErlandssonA** [comment] 2021-07-05 12:06
I also have this issue, have anyone found a fix for it?

**Comment by maruohon** [comment] 2021-07-06 15:28
I need some way to reproduce the issue. Is it maybe dependant on the GPU manufacturer/drivers?
Like I mentioned it works as expected for me atm:
https://user-images.githubusercontent.com/2331050/124626955-cdd26100-de87-11eb-8bfd-b98e41ce5659.mp4

(The margin increasing by the scale value is actually not intended, but that bug has always existed. It's fixed in the development code where most things are being rewritten and cleaned up.)

**Comment by maruohon** [comment] 2021-07-06 22:40
I figured out what the issue/difference was: if the text background color was disabled, then the font scaling broke. I fixed this in the new malilib build for MC 1.17.1.

**Closed as completed** 2021-07-14 22:53 UTC
Labels: in-malilib
